### PR TITLE
Make meta_tags fail gracefully

### PR DESCRIPTION
**Pull request by bruecksen**
This will fix issue #51

### CODE REVIEW

**Comment by bruecksen** [comment]
@seb-b yes you are right, don't know how I ended up in this path. I now switched to your solution and it is working great. Thanks for the hint in the right direction.

**Comment by Pomax** [comment]
This does not help with https://github.com/neon-jungle/wagtail-metadata/issues/51 though - in order to ensure the 404 looks exactly like the main sites (plural), they extend their base.html with wagtail metadata block. Which, of course, those 404 can be given a `{% block wagtail_metadata %}{% endblock %}` override, when someone _forgets_ that (and that's what we're trying to catch here - things going wrong, not things going right =) that 404 trying to load metadata from an object that doesn't exist, _while serving the 404_ means instead there's a silent crash and the most useless "server 500" page getting server with nothing in the logs because debug is False in production.

So I'd strongly urge reopening this PR because things working when the code is clean does not help prevent production crashes when someone accidentally lands something that isn't.

**Comment by seb-b** [comment]
@Pomax I'm not sure how including the meta-tags allows the 404 pages to look like other pages in your site?

You could include a check around your meta tag output, essentially what this pr does, if it's not possible to rearrange your template hierachy:

```html+django
{% if self and 'request' in self %}
   {% meta_tags %}
{% endif %}
```

**Comment by Pomax** [comment]
it's not: extending base.html does. So 404.html extends base.html and base.html loads in the wagtail metadata because except for a truly tiny number of things, everything is wagtail-managed. 404s are in that tiny subset, though, and a commit landed that did not blank out the block for wagtail metadata. Cue production crashing on 404s.

And no one caught it, because there is no way to catch it: with debug=True, you never see the 404, and with debug=False, you never see the log, so the only way to know this is going to be a problem is for the metadata tag to go "uh, you called me, but not for a model that supports me: that's a bug and you should fix that" in the log, while rendering as an empty string.

**Pull request closed without merging**
